//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroondasAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antena
    {
        public System.Guid idAntena { get; set; }
        public Nullable<System.Guid> idEstado { get; set; }
        public Nullable<System.Guid> idCiudad { get; set; }
        public Nullable<System.Guid> idCP { get; set; }
        public Nullable<System.Guid> idColonia { get; set; }
        public string calle { get; set; }
        public Nullable<int> numExt { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<decimal> lat { get; set; }
        public Nullable<decimal> lon { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Colonia Colonia { get; set; }
        public virtual CodigoPostal CodigoPostal { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
