//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroondasAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informes
    {
        public System.Guid idInformes { get; set; }
        public string nombre { get; set; }
        public Nullable<int> cp { get; set; }
        public string telefono { get; set; }
        public Nullable<bool> visto { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
