//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroondasAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public System.Guid idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string telefono { get; set; }
        public string correoE { get; set; }
        public string calle { get; set; }
        public string numInt { get; set; }
        public Nullable<int> numExt { get; set; }
        public Nullable<System.Guid> idColonia { get; set; }
        public Nullable<System.Guid> idCP { get; set; }
        public Nullable<System.Guid> idRol { get; set; }
        public Nullable<System.Guid> idContrato { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual CodigoPostal CodigoPostal { get; set; }
        public virtual Colonia Colonia { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
